apiVersion: v2
name: confluence
description: A chart for installing Confluence Data Center on Kubernetes
type: application
version: 1.10.20
appVersion: 7.19.5
kubeVersion: ">=1.21.x-0"
keywords:
- Confluence
- Confluence Server
- Confluence Data Center
- Confluence DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/confluence.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |-
    - "Update appVersion in DC apps"
    - "Refactor confluence chart to implement a new feature"
    - "Remove confluence helmfile to update dependencies"
    - "Merge confluence statefulset for better maintainability"
    - "Refactor confluence statefulset to implement a new feature"
    - "Move confluence helmfile to implement a new feature"
    - "Remove confluence dependencies to improve performance"
    - "Update confluence statefulset to implement a new feature"
    - "Remove confluence values to enhance flexibility"

dependencies:
- name: common
  version: 1.0.0
  repository: https://atlassian.github.io/data-center-helm-charts
