apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: 1.10.33
appVersion: 7.21.11
kubeVersion: ">=1.21.x-0"
keywords:
- Bitbucket
- Bitbucket Server
- Bitbucket Data Center
- Bitbucket DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Update appVersion in DC apps"
    - "Optimize bitbucket dependencies for better readability"
    - "Remove bitbucket chart to remove deprecated code"
    - "Fix bitbucket tests to improve performance"
    - "Update bitbucket values to update dependencies"
    - "Move bitbucket chart to enhance flexibility"
    - "Move bitbucket documentation to implement a new feature"
    - "Remove bitbucket helmfile for better maintainability"
    - "Fix bitbucket statefulset to update dependencies"
    - "Refactor bitbucket statefulset for better readability"
    - "Rework bitbucket templates for better maintainability"
    - "Update bitbucket documentation to optimize memory usage"
    - "Add bitbucket tests for better maintainability"

dependencies:
- name: common
  version: 1.0.0
  repository: https://atlassian.github.io/data-center-helm-charts
