apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: 1.10.31
appVersion: 9.4.3
kubeVersion: ">=1.21.x-0"
keywords:
- Jira
- Jira Software
- Jira Server
- Jira Data Center
- Jira DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Update appVersion in DC apps"
    - "Remove jira documentation to fix a bug"
    - "Move jira dependencies to fix a bug"
    - "Optimize jira values for better readability"
    - "Merge jira dependencies to implement a new feature"
    - "Rework jira tests for better maintainability"
    - "Refactor jira tests to remove deprecated code"
    - "Remove jira templates for better maintainability"
    - "Update jira chart for better maintainability"

dependencies:
- name: common
  version: 1.0.0
  repository: https://atlassian.github.io/data-center-helm-charts
