apiVersion: v2
name: bamboo
description: A chart for installing Bamboo Data Center on Kubernetes
type: application
version: 1.10.31
appVersion: 9.2.2
kubeVersion: ">=1.21.x-0"
keywords:
- Bamboo
- Bamboo Server
- Bamboo Data Center
- Bamboo DC
- Atlassian
home: https://www.atlassian.com/software/bamboo
icon: https://atlassian.github.io/data-center-helm-charts/icons/bamboo.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-bamboo-server
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Update appVersion in DC apps"
    - "Merge bamboo values to enhance flexibility"
    - "Refactor bamboo statefulset for better readability"
    - "Rework bamboo helmfile for better maintainability"
    - "Optimize bamboo tests for better readability"
    - "Update bamboo templates to fix a bug"
    - "Optimize bamboo values to implement a new feature"
    - "Move bamboo chart to improve performance"
    - "Fix bamboo dependencies to remove deprecated code"
dependencies:
- name: common
  version: 1.0.0
  repository: https://atlassian.github.io/data-center-helm-charts
