apiVersion: v2
name: bamboo
description: A chart for installing Bamboo Data Center on Kubernetes
type: application
version: 1.10.29
appVersion: 9.2.2
kubeVersion: ">=1.21.x-0"
keywords:
- Bamboo
- Bamboo Server
- Bamboo Data Center
- Bamboo DC
- Atlassian
home: https://www.atlassian.com/software/bamboo
icon: https://atlassian.github.io/data-center-helm-charts/icons/bamboo.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-bamboo-server
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Update appVersion in DC apps"
    - "Remove bamboo chart to implement a new feature"
    - "Update bamboo dependencies to improve performance"
    - "Fix bamboo dependencies to improve performance"
    - "Remove bamboo values to update dependencies"
dependencies:
- name: common
  version: 1.0.0
  repository: https://atlassian.github.io/data-center-helm-charts
