# This workflow is for testing Helm charts in KinD clusters

name: Test Secrets

on:
  workflow_dispatch:
  pull_request_target:
    types: [ labeled ]

jobs:
  test:
    if: ${{ github.event.label.name == 'kind' || github.event_name == 'workflow_dispatch' }}
    name: Test secrets availability
    runs-on: ubuntu-latest
    env:
      HELM_SIGNING_KEY_ID: ${{ secrets.HELM_SIGNING_KEY_ID }}

    steps:
      - name: Source code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test if secret is available
        run: |
          if [ -n "$HELM_SIGNING_KEY_ID" ]; then
              echo "HELM_SIGNING_KEY_ID is $HELM_SIGNING_KEY_ID"
          else
              echo "HELM_SIGNING_KEY_ID is empty"
              exit 1
          fi