# This workflow is for testing Helm charts in KinD clusters

name: Test Secrets

on:
  workflow_dispatch:
  pull_request_target:
    types: [ labeled ]

jobs:
  test:
    if: ${{ github.event.label.name == 'kind' || github.event_name == 'workflow_dispatch' }}
    name: Test secrets availability
    runs-on: ubuntu-latest
    env:
      HELM_SIGNING_KEY_ID: ${{ secrets.HELM_SIGNING_KEY_ID }}

    steps:
      - name: Source code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: test terraform
        run: |
          # check existing version
          terraform --verion
          
          # download the latest
          URL=$(curl -fsSL https://api.releases.hashicorp.com/v1/releases/terraform/latest | jq -r '.builds[] | select((.arch=="amd64") and (.os=="linux")).url')
          curl -o /tmp/terraform.zip ${URL}
          unzip /tmp/terraform.zip -d /usr/local/bin/
          rm /tmp/terraform.zip
          
          # check the latest version
          terraform --verion
      - name: Test if secret is available
        run: |
          if [ -n "$HELM_SIGNING_KEY_ID" ]; then
              echo "HELM_SIGNING_KEY_ID is $HELM_SIGNING_KEY_ID"
          else
              echo "HELM_SIGNING_KEY_ID is empty"
              exit 1
          fi
