name: Release Helm Charts

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PYTHONPATH: /opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.4

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.14'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip gitpython ruamel_yaml

      - name: Generate Release Notes for GitHub Releases
        run: |
          cd src/main/scripts
          ./release_notes_generator.sh ${GITHUB_WORKSPACE}

      - name: Release Helm Charts
        run: |
          src/main/scripts/generate_chart_repo.sh ${GH_TOKEN}

      - name: Commit and push index.yaml
        run: |
          git commit -m "Update index.yaml post release"