name: Test git log

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        ref: refs/heads/main

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
          git tag
          
          git log --graph --pretty=format:%s --abbrev-commit --date=relative bamboo-1.10.8..main -- src/main/charts/bamboo
